### ISSUE TITLE
First Gen LON needs to report LON region

### ISSUE THREAD

**Issue by rtgoodwin** [rackerlabs/cs-reboot-info#50]
If a valid FG endpoint is found in LON, we need to ensure we show the LON region (which can be hardcoded) and not any other hardcoded values.

**Comment by smashwilson** [comment]
How can we distinguish an LON account from a US account, now that both use the same identity endpoint?

My first instinct is to see if the regions slice contains exactly `[]string{"LON"}`.

**Comment by rtgoodwin** [comment]
That should work, there's only one valid region return for region/compute endpoint for LON.  Just verify it with a dump to be safe.

**Comment by ckuehl** [comment]
Not sure if this is related, but this is what I'm seeing on a test account that has FG LON servers:

Regions with a Cloud Servers endpoint: LON
Found both First and Next Generation endpoints.
Error listing servers: 8 error(s) decoding:

* 'servers[0].ID' expected type 'string', got unconvertible type 'float64'
* 'servers[1].ID' expected type 'string', got unconvertible type 'float64'
* 'servers[2].ID' expected type 'string', got unconvertible type 'float64'
* 'servers[3].ID' expected type 'string', got unconvertible type 'float64'
* 'servers[4].ID' expected type 'string', got unconvertible type 'float64'
* 'servers[5].ID' expected type 'string', got unconvertible type 'float64'
* 'servers[6].ID' expected type 'string', got unconvertible type 'float64'
* 'servers[7].ID' expected type 'string', got unconvertible type 'float64'
(followed by output for my NG servers)

Let me know if I need to open a separate issue for this.

**Comment by rtgoodwin** [comment]
Yes build is currently broken for FG due to dependency issue. Glad you have the servers to test on that account!

**Comment by rtgoodwin** [comment]
FYI @ckuehl added credentials to internal test list for regression.
