### ISSUE TITLE
Region incorrect for First Gen Cloud Servers

### ISSUE THREAD

**Issue by ckuehl** [rackerlabs/cs-reboot-info#63]
The First Gen Cloud Servers output is displaying DFW as the region, regardless of the actual region.

**Comment by jnoller** [comment]
@ckuehl On the output, or are we missing regions?

**Comment by ckuehl** [comment]
@jnoller In the output. I believe there are a couple of options:

1) Use the /v1.1 version of the Cloud Servers API which should show the region for each server
2) Remove the region output on First Gen servers (possibly easier)

**Comment by jnoller** [comment]
thanks, on it.

**Comment by jamiehannaford** [comment]
@ckuehl Hey Chris, can you try this new binary:

> https://a4fae0f0d6cf4cc92acd-d6ce857812540f8fb39144d83ca6538f.ssl.cf5.rackcdn.com/releases/test_1.1/cs-reboot-info_darwin_386

(assuming you're running OS X Darwin 386).

**Comment by ckuehl** [comment]
@jamiehannaford Trying it now and will let you know shortly.

**Comment by ckuehl** [comment]
@jamiehannaford Looks good. I'm now seeing the First Gen servers show up without a region, which should work well. I tested in both LON and ORD. Thanks!
