### ISSUE TITLE
Timezones off?

### ISSUE THREAD

**Issue by smashwilson** [rackerlabs/cs-reboot-info#75]
From an email:

> Hey Ash, 
>
> I came across an issue today. Customer was using the toll cs-reboot-info and its giving conflicting times and timezones compared to tickets that are being sent out. Just wanted to alert you in case the script is in error.  I attempted to ask our CSO team which was correct and they told me the ticket information was correct, not the cs-reboot-info UTC time.   
>
You’ll see that the UTC time listed, and the CDT time in the ticket do not match up.
>
> [...]
>
> Sincerely,
>
> Joey Davis
> Managed Infrastructure Support

**Comment by rtgoodwin** [comment]
This is true; the tool wasn't designed for local time zones as I recall; could we knock in something to detect the machine local time zone (on which the tool is being run) and apply it to the API calls? Although I'm not sure if all calls support the time zone transformation: https://developer.rackspace.com/docs/cloud-servers/v2/developer-guide/#list-servers-with-details

**Comment by smashwilson** [comment]
We're parsing the timestamps from text that's retrieved from a Nova metadata field, so the timezone parsing is entirely done within Go.

I'm just wondering if they've changed the format of that string on us.

**Comment by rtgoodwin** [comment]
Right, I just thought we decided to to not do local timezones since the tool local might not be the same as the servers (almost certainly wouldn't be). Could be an option.
Richard Goodwin
Product Manager - Mobile, Developer Experience
Ideation | Intellection | Activator | Relator | Responsibility
Phone: (512) 788 5403 - Cell: (512) 736-7897 (Austin)
Skype: rtgoodwin<file:///callto/::rtgoodwin> - Yahoo: richardtgoodwin<file:///ymsgr/sendim%3Frichardtgoodwin>
AIM: dellovision - IRC: goody / rgoodwin

**Comment by smashwilson** [comment]
We're showing both [local and UTC in separate columns](https://github.com/rackerlabs/cs-reboot-info/blob/master/output-tabular.go#L50). That's fine, but it looks like, at least for this particular customer, the timestamps in their metadata are inconsistent with the timestamps that were provided to them in a ticket.

We need to trace down which is wrong, and if it's just wrong for this customer, or for _all_ customers in this batch of reboots. Who do we talk to about this?

**Comment by rtgoodwin** [comment]
Are we good to close this now, since it seemed to be bad server side metadata?

**Comment by smashwilson** [comment]
:+1: Sounds good to me. :confetti_ball:
